### ISSUE TITLE
Player move lists leak off of the screen.

### ISSUE THREAD

**Issue by MwKau** [CarrC2021/AndroidChessProject#16]
The GUI for displaying previous moves eventually exceeds the size of the screen and cannot be seen.

Severity: Minor
Component: GUI

While testing on ASUS028, the list of previous moves exceeds the GUI space allocated for displaying previous moves after the 23rd move, causing the rest of the list to be hidden. This doesn't seem to have any effect on the game play.

To recreate this bug, the user needs to start a game with a human and computer AI, then make complete moves 11 times. Then on the 12th move, the text under "White Player's Moves:" is hidden.

**Comment by saligumb22** [comment]
Changed the display moves list so that they appear horizontally, and there is more space so that they do not move off the screen.

**Comment by MwKau** [comment]
This is helpful, but a temporary fix.
